module.exports = {
  env: {
    GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
    FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
    GRAPHQL:process.env.GRAPHQL,
    MORF_DOMAIN:process.env.MORF_DOMAIN,
    MAILCHIMP_POST_API:process.env.MAILCHIMP_POST_API,
    MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
    MAILCHIMP_LIST_ID:process.env.MAILCHIMP_LIST_ID,
    MAILCHIMP_U_VALUE: process.env.MAILCHIMP_U_VALUE,
    MAILCHIMP_FORM_ID:process.env.MAILCHIMP_FORM_ID,
    NEXT_PUBLIC_S3ASSETS_URL: process.env.NEXT_PUBLIC_S3ASSETS_URL,
    RAZORPAY_KEY:process.env.RAZORPAY_KEY
  }
};
