export default [
  {
    id: 1,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    category: "Leather lace-up",
    quantity: 1,
    price: 3999,
    href: "/",
    height: 600,
    type: "product",
  },

  // {
  //   id: 2,
  //   src: "/images/homepageImg/Component66.jpg",
  //   hoverState: "images/homepageImg/Component66.jpg",
  //   category: "Leather lace-up",
  //   price: 3999,
  //   quantity: 1,
  //   href: "/",
  //   height: 600,
  //   type: "product",
  // },

  // {
  //   id: 2,
  //   text: "A highly curated selection of products we believe in",
  //   type: "text",
  //   height: 600,
  // },

  {
    id: 2,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 3,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component61.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 4,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component66.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 5,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component65_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 6,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component66_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 7,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component68_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 8,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component61_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 9,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component69_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 10,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component70_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },

  {
    id: 11,
    src: "https://morf-gray.vercel.app/images/homepageImg/Component61_H.jpg",
    hoverState: "images/homepageImg/Component70_H.jpg",
    category: "Leather lace-up",
    price: 3999,
    quantity: 1,
    href: "/",
    height: 600,
    type: "product",
  },
];
